// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdS4pJb0UdgxRCBENkVPxfAFZ7xwvQcg',
    appId: '1:228677570502:web:3d49c16a293d18aef56cc7',
    messagingSenderId: '228677570502',
    projectId: 'interview-41f79',
    authDomain: 'interview-41f79.firebaseapp.com',
    databaseURL: 'https://interview-41f79-default-rtdb.firebaseio.com',
    storageBucket: 'interview-41f79.firebasestorage.app',
    measurementId: 'G-KD54727BE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0PH5CNEMwKPsY6mCZ62VET6zECRWOjP0',
    appId: '1:228677570502:android:7d2b4c9351ebd8d7f56cc7',
    messagingSenderId: '228677570502',
    projectId: 'interview-41f79',
    databaseURL: 'https://interview-41f79-default-rtdb.firebaseio.com',
    storageBucket: 'interview-41f79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpCpJY6qf-_43Cpdw5HbTm_fOawA70o54',
    appId: '1:228677570502:ios:2cf359526e2f48f7f56cc7',
    messagingSenderId: '228677570502',
    projectId: 'interview-41f79',
    databaseURL: 'https://interview-41f79-default-rtdb.firebaseio.com',
    storageBucket: 'interview-41f79.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpCpJY6qf-_43Cpdw5HbTm_fOawA70o54',
    appId: '1:228677570502:ios:2cf359526e2f48f7f56cc7',
    messagingSenderId: '228677570502',
    projectId: 'interview-41f79',
    databaseURL: 'https://interview-41f79-default-rtdb.firebaseio.com',
    storageBucket: 'interview-41f79.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWdS4pJb0UdgxRCBENkVPxfAFZ7xwvQcg',
    appId: '1:228677570502:web:ba146fef009e922af56cc7',
    messagingSenderId: '228677570502',
    projectId: 'interview-41f79',
    authDomain: 'interview-41f79.firebaseapp.com',
    databaseURL: 'https://interview-41f79-default-rtdb.firebaseio.com',
    storageBucket: 'interview-41f79.firebasestorage.app',
    measurementId: 'G-DFQ5WBT1J1',
  );
}
