// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUrzgupizSmYI8ITLYxYeOJf1oEXrKZI',
    appId: '1:363864331050:web:6776752af49a077858c453',
    messagingSenderId: '363864331050',
    projectId: 'construction-app-10060',
    authDomain: 'construction-app-10060.firebaseapp.com',
    databaseURL: 'https://construction-app-10060-default-rtdb.firebaseio.com',
    storageBucket: 'construction-app-10060.firebasestorage.app',
    measurementId: 'G-DE5SC9X9HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVdafVKaPzdqZspTov0GIKW1JteG148j8',
    appId: '1:363864331050:android:3d18e2a7086b021458c453',
    messagingSenderId: '363864331050',
    projectId: 'construction-app-10060',
    databaseURL: 'https://construction-app-10060-default-rtdb.firebaseio.com',
    storageBucket: 'construction-app-10060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pPcAntSufuk9G6MgJ4nO0M4QMR7gR-k',
    appId: '1:363864331050:ios:b80caca73eb7a14f58c453',
    messagingSenderId: '363864331050',
    projectId: 'construction-app-10060',
    databaseURL: 'https://construction-app-10060-default-rtdb.firebaseio.com',
    storageBucket: 'construction-app-10060.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pPcAntSufuk9G6MgJ4nO0M4QMR7gR-k',
    appId: '1:363864331050:ios:b80caca73eb7a14f58c453',
    messagingSenderId: '363864331050',
    projectId: 'construction-app-10060',
    databaseURL: 'https://construction-app-10060-default-rtdb.firebaseio.com',
    storageBucket: 'construction-app-10060.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUrzgupizSmYI8ITLYxYeOJf1oEXrKZI',
    appId: '1:363864331050:web:18ce76fbbde6d7ab58c453',
    messagingSenderId: '363864331050',
    projectId: 'construction-app-10060',
    authDomain: 'construction-app-10060.firebaseapp.com',
    databaseURL: 'https://construction-app-10060-default-rtdb.firebaseio.com',
    storageBucket: 'construction-app-10060.firebasestorage.app',
    measurementId: 'G-3JE76FS231',
  );
}
